In [2]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [44]:
arr = np.array([[ 0,  1,  2],
                [10, 11, 12],
                [20, 21, 22],
                [30, 31, 32],
                [40, 41, 42],
                [50, 51, 52],
                [60, 61, 62]])   # shape = (7, 3)
arr[2:5, [1, 2]]

array([[21, 22],
       [31, 32],
       [41, 42]])

In [6]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
df = pd.read_excel("Time-Table, FSC, Fall-2025.xlsx", sheet_name= "Monday", header= 4)
clean_df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
clean_df = clean_df.dropna(subset=['Room'])
clean_df = clean_df.fillna("NIL")
clean_df

,Room,08:30-09:50,10:00-11:20,11:30-12:50,01:00-02:20,02:30-03:50,03:55-05:15,05:20-06:40,06:45-08:05
0,C-301,PF (CS-A),AP (CS-A),Calculus (CS-A),NIL,NIL,NIL,App Prog (CS),NIL
1,C-302,AP (CS-B),PF (CS-B),Calculus (CS-B),Tutorial (25),Tutorial (25),NIL,App Prog (CY/SE),NIL
2,C-303,PF (CS-C),Calculus (CS-C),AP (CS-C),Tutorial (25),Ideology of Pak (CS-C) 02:30-04:15,NIL,App Prog (AI),NIL
3,C-304,Calculus (CS-D),PF (CS-D),AP (CS-D),NIL,Func Eng (CS-D) 02:30-04:15,NIL,Data Sci Tools & Tech (DS),Stat & Math for DS (DS)
4,C-305,Islamic (CS-H) 08:30-10:15,NIL,Islamic (CS-G) 11:30-01:15,NIL,NIL,NIL,NLP (DS),NLP (DS)
...,...,...,...,...,...,...,...,...,...
70,A-Mehran 2,Func Eng Lab (CS-F1),NIL,Func Eng Lab (SE-C1),NIL,Func Eng Lab (AI-A1),NIL,NIL,NIL
71,A-CALL-1,FSM,NIL,FSM,NIL,Func Eng Lab (AI-A2),NIL,NIL,NIL
72,A-CALL-2,FSM,NIL,FSM,NIL,Func Eng Lab (CS-E1),NIL,NIL,NIL
73,A-CALL-3,Func Eng Lab (CS-F2),NIL,Func Eng Lab (SE-C2),NIL,Func Eng Lab (CS-E2),NIL,NIL,NIL
74,B-Digital,DLD Lab (SE-A),NIL,NIL,NIL,NIL,NIL,NIL,NIL